### ISSUE TITLE
HTML - Add place holders for desired pages

### ISSUE THREAD

**Issue by dmeissner** [bbeaber337/Classroom-Scheduler#16]
Add blank pages to the navigation thingy for the planned pages.

**Comment by plato360** [comment]
Added placeholders for most (now has class, classroom, teacher, conflict, semester, and user) of the view pages, still needs code to actually show the lists for teacher, conflict, and semester

**Comment by dmeissner** [comment]
Tim has added the remaining needed code for the pages.
